import Foundation
import DocumentCore

/// Expected page-space geometry for one alignment fixture, written to
/// `alignment.json` next to the PDFs. Boxes and `squareUserRect` are PDF user
/// space; `expectedPageRect` and `displaySize` are page space.
public struct AlignmentExpectation: Codable, Hashable, Sendable {
    public var file: String
    public var rotation: Int
    public var mediaBox: PageRect
    public var cropBox: PageRect
    /// The filled 20 pt square as drawn, in PDF user space.
    public var squareUserRect: PageRect
    /// Where the square must appear in page space (origin top-left of the rotated, cropped page).
    public var expectedPageRect: PageRect
    public var displaySize: PageSize
    public var label: String
    public init(file: String, rotation: Int, mediaBox: PageRect, cropBox: PageRect, squareUserRect: PageRect,
                expectedPageRect: PageRect, displaySize: PageSize, label: String) {
        self.file = file; self.rotation = rotation; self.mediaBox = mediaBox; self.cropBox = cropBox
        self.squareUserRect = squareUserRect; self.expectedPageRect = expectedPageRect; self.displaySize = displaySize; self.label = label
    }
}

public struct AlignmentSidecar: Codable, Hashable, Sendable {
    public var formatVersion: Int
    public var note: String
    public var fixtures: [AlignmentExpectation]
    public init(formatVersion: Int = 1, note: String, fixtures: [AlignmentExpectation]) {
        self.formatVersion = formatVersion; self.note = note; self.fixtures = fixtures
    }
}

/// A named, deterministic fixture and how to produce its bytes.
public struct Fixture: Sendable {
    public var name: String
    /// Path relative to the fixture output directory (may contain a subdirectory).
    public var relativePath: String
    public var generate: @Sendable () throws -> Data
    public init(name: String, relativePath: String, generate: @escaping @Sendable () throws -> Data) {
        self.name = name; self.relativePath = relativePath; self.generate = generate
    }
}

/// Every fixture the repository ships in `Fixtures/`, regenerated by
/// `swift run fixturegen <outputDir>` (Scripts/generate-fixtures.sh).
public enum FixtureCatalog {
    public static let letter = PageRect(x: 0, y: 0, width: 612, height: 792)
    public static let a4 = PageRect(x: 0, y: 0, width: 595.276, height: 841.89)
    public static let letterLandscape = PageRect(x: 0, y: 0, width: 792, height: 612)

    // MARK: Alignment fixtures

    /// The 20 pt square every alignment page draws (PDF user space).
    public static let alignmentSquare = PageRect(x: 100, y: 150, width: 20, height: 20)
    /// Crop boxes: 504 × 666 pt at the two origins. Both lie inside the Letter media box.
    public static let alignmentCropBoxes: [(origin: (Int, Int), box: PageRect)] = [
        ((0, 0), PageRect(x: 0, y: 0, width: 504, height: 666)),
        ((36, 54), PageRect(x: 36, y: 54, width: 504, height: 666)),
    ]

    /// Hand-derived expectations (see `PageGeometry.PageMapping` for the general
    /// derivation). With crop `[cx0 cy0 cx1 cy1]` and the square spanning
    /// x ∈ [100,120], y ∈ [150,170] in user space:
    ///
    ///     0:   X = x − cx0,  Y = cy1 − y
    ///     90:  X = y − cy0,  Y = x − cx0
    ///     180: X = cx1 − x,  Y = y − cy0
    ///     270: X = cy1 − y,  Y = cx1 − x
    ///
    /// Crop A `[0 0 504 666]`:
    ///     0:   x∈[100,120]         → X∈[100,120]; Y = 666−[150,170] → [496,516]  ⇒ (100, 496)
    ///     90:  X = y ∈[150,170];      Y = x ∈[100,120]                          ⇒ (150, 100)
    ///     180: X = 504−x ∈[384,404];  Y = y ∈[150,170]                          ⇒ (384, 150)
    ///     270: X = 666−y ∈[496,516];  Y = 504−x ∈[384,404]                      ⇒ (496, 384)
    /// Crop B `[36 54 540 720]`:
    ///     0:   X = x−36 ∈[64,84];     Y = 720−y ∈[550,570]                      ⇒ (64, 550)
    ///     90:  X = y−54 ∈[96,116];    Y = x−36 ∈[64,84]                         ⇒ (96, 64)
    ///     180: X = 540−x ∈[420,440];  Y = y−54 ∈[96,116]                        ⇒ (420, 96)
    ///     270: X = 720−y ∈[550,570];  Y = 540−x ∈[420,440]                      ⇒ (550, 420)
    public static let alignmentExpectations: [AlignmentExpectation] = {
        let expectedOrigins: [String: (Double, Double)] = [
            "0-0x0": (100, 496), "90-0x0": (150, 100), "180-0x0": (384, 150), "270-0x0": (496, 384),
            "0-36x54": (64, 550), "90-36x54": (96, 64), "180-36x54": (420, 96), "270-36x54": (550, 420),
        ]
        var out: [AlignmentExpectation] = []
        for rotation in [0, 90, 180, 270] {
            for (origin, crop) in alignmentCropBoxes {
                let key = "\(rotation)-\(origin.0)x\(origin.1)"
                let (ex, ey) = expectedOrigins[key]!
                let swap = rotation == 90 || rotation == 270
                out.append(AlignmentExpectation(
                    file: "alignment-\(key).pdf", rotation: rotation, mediaBox: letter, cropBox: crop,
                    squareUserRect: alignmentSquare,
                    expectedPageRect: PageRect(x: ex, y: ey, width: 20, height: 20),
                    displaySize: swap ? PageSize(width: crop.height, height: crop.width) : PageSize(width: crop.width, height: crop.height),
                    label: "rotate \(rotation) crop \(origin.0),\(origin.1)"))
            }
        }
        return out
    }()

    public static func alignmentPage(_ e: AlignmentExpectation) -> PDFFixturePage {
        PDFFixturePage(mediaBox: e.mediaBox, cropBox: e.cropBox, rotate: e.rotation, ops: [
            .strokeRect(e.cropBox, width: 0.5),
            .fillRect(e.squareUserRect, gray: 0),
            .text(e.label, x: 100, y: 200, size: 12),
            .text("square at user (100,150)-(120,170)", x: 100, y: 130, size: 9),
        ])
    }

    public static func alignmentSidecarData() throws -> Data {
        let sidecar = AlignmentSidecar(
            note: "Each PDF draws a filled 20 pt square at squareUserRect (PDF user space). After cropping and /Rotate, "
                + "PageGeometry.PageMapping must place it at expectedPageRect in page space (origin top-left, y down).",
            fixtures: alignmentExpectations)
        return try DocumentJSON.encoder().encode(sidecar)
    }

    // MARK: Other fixtures

    public static func longMixedPages(count: Int = 300) -> [PDFFixturePage] {
        (0..<count).map { i in
            let box: PageRect
            switch i % 3 {
            case 0: box = letter
            case 1: box = a4
            default: box = letterLandscape
            }
            return PDFFixturePage(mediaBox: box, ops: [
                .text("Page \(i + 1) of \(count)", x: 72, y: box.maxY - 72, size: 14),
                .line(from: PagePoint(x: 72, y: box.maxY - 80), to: PagePoint(x: box.maxX - 72, y: box.maxY - 80), width: 0.5),
            ])
        }
    }

    public static func textAndOutlinePages() -> [PDFFixturePage] {
        let chapters = ["Chapter 1: Kinematics", "Chapter 2: Dynamics", "Chapter 3: Energy & Work"]
        return chapters.enumerated().map { i, title in
            PDFFixturePage(mediaBox: letter, ops: [
                .text(title, x: 72, y: 720, size: 18),
                .text("Problem \(i + 1). A body moves along a straight line.", x: 72, y: 690, size: 11),
                .text("Find the displacement after t seconds.", x: 72, y: 674, size: 11),
                .strokeRect(PageRect(x: 72, y: 400, width: 468, height: 200), width: 1),
            ], outlineTitle: title)
        }
    }

    public static func imageOnlyPages() -> [PDFFixturePage] {
        let w = 24, h = 16
        var rgb: [UInt8] = []
        for y in 0..<h { for x in 0..<w { rgb += [UInt8(x * 255 / (w - 1)), UInt8(y * 255 / (h - 1)), (x + y) % 2 == 0 ? 220 : 30] } }
        let image = PDFFixtureImage(width: w, height: h, rgb: rgb, frame: PageRect(x: 72, y: 432, width: 468, height: 312))
        return [PDFFixturePage(mediaBox: letter, image: image)]
    }

    /// A valid PDF whose xref offsets are all shifted by 5 bytes (object 0 untouched).
    public static func badXrefData() -> Data {
        var bytes = [UInt8](MinimalPDFWriter.write(pages: textAndOutlinePages()))
        guard let sx = PDFXrefChecker.lastRange(of: Array("startxref".utf8), in: bytes) else { return Data(bytes) }
        var c = sx.upperBound
        PDFXrefChecker.skipWhitespace(bytes, &c)
        guard let start = PDFXrefChecker.readInt(bytes, &c) else { return Data(bytes) }
        // Skip "xref\n0 N\n" then the free entry, then rewrite each in-use entry.
        var cursor = start + 4
        PDFXrefChecker.skipWhitespace(bytes, &cursor)
        _ = PDFXrefChecker.readInt(bytes, &cursor); PDFXrefChecker.skipWhitespace(bytes, &cursor)
        guard let count = PDFXrefChecker.readInt(bytes, &cursor) else { return Data(bytes) }
        PDFXrefChecker.skipWhitespace(bytes, &cursor)
        for i in 0..<count {
            let entryStart = cursor
            cursor += 20
            guard i > 0 else { continue }
            let text = String(decoding: bytes[entryStart..<entryStart + 10], as: UTF8.self)
            guard let off = Int(text) else { continue }
            let shifted = String(off + 5).leftPadded(to: 10)
            bytes.replaceSubrange(entryStart..<entryStart + 10, with: Array(shifted.utf8))
        }
        return Data(bytes)
    }

    public static func garbageData(byteCount: Int = 4096) -> Data {
        var rng = FixtureRandom(seed: 0xC0FFEE)
        var bytes: [UInt8] = []
        bytes.reserveCapacity(byteCount)
        while bytes.count < byteCount {
            let v = rng.next()
            for shift in stride(from: 0, to: 64, by: 8) where bytes.count < byteCount { bytes.append(UInt8((v >> UInt64(shift)) & 0xFF)) }
        }
        // Make sure no PDF header can appear by accident.
        if bytes.count > 5 { bytes.replaceSubrange(0..<5, with: Array("GARBG".utf8)) }
        return Data(bytes)
    }

    public static func truncatedData() -> Data {
        let full = MinimalPDFWriter.write(pages: textAndOutlinePages())
        return full.prefix(full.count * 3 / 5)
    }

    // MARK: Catalog

    public static let all: [Fixture] = {
        var list: [Fixture] = []
        for e in alignmentExpectations {
            list.append(Fixture(name: e.file.replacingOccurrences(of: ".pdf", with: ""), relativePath: e.file) {
                MinimalPDFWriter.write(pages: [alignmentPage(e)])
            })
        }
        list.append(Fixture(name: "alignment-sidecar", relativePath: "alignment.json") { try alignmentSidecarData() })
        list.append(Fixture(name: "long-300-mixed", relativePath: "long-300-mixed.pdf") { MinimalPDFWriter.write(pages: longMixedPages()) })
        list.append(Fixture(name: "text-and-outline", relativePath: "text-and-outline.pdf") { MinimalPDFWriter.write(pages: textAndOutlinePages()) })
        list.append(Fixture(name: "image-only", relativePath: "image-only.pdf") { MinimalPDFWriter.write(pages: imageOnlyPages()) })
        list.append(Fixture(name: "encrypted-marker", relativePath: "encrypted-marker.pdf") {
            MinimalPDFWriter.write(pages: textAndOutlinePages(), markEncrypted: true)
        })
        list.append(Fixture(name: "malformed-truncated", relativePath: "malformed/truncated.pdf") { truncatedData() })
        list.append(Fixture(name: "malformed-garbage", relativePath: "malformed/garbage.pdf") { garbageData() })
        list.append(Fixture(name: "malformed-bad-xref", relativePath: "malformed/bad-xref.pdf") { badXrefData() })
        list.append(Fixture(name: "sample-png", relativePath: "sample.png") { MinimalPNGWriter.sampleImage(width: 32, height: 24) })
        list.append(Fixture(name: "dense-ink-500", relativePath: "ink/dense-500.json") {
            try ReferenceInkEngine().encode(InkFixtures.denseDrawing(strokeCount: 500, seed: 7))
        })
        list.append(Fixture(name: "partially-erased-ink", relativePath: "ink/partially-erased.json") {
            try ReferenceInkEngine().encode(InkFixtures.partiallyErasedSample())
        })
        return list
    }()

    public static func fixture(named name: String) -> Fixture? { all.first { $0.name == name } }

    /// Generates the fixture bytes by name.
    public static func data(named name: String) throws -> Data {
        guard let f = fixture(named: name) else { throw FixtureError.unknownFixture(name) }
        return try f.generate()
    }

    /// Writes every fixture under `directory` (created if needed) and returns the written URLs in catalog order.
    @discardableResult
    public static func writeAll(to directory: URL) throws -> [URL] {
        let fm = FileManager.default
        try fm.createDirectory(at: directory, withIntermediateDirectories: true)
        var urls: [URL] = []
        for f in all {
            let url = directory.appendingPathComponent(f.relativePath)
            try fm.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
            try f.generate().write(to: url, options: .atomic)
            urls.append(url)
        }
        return urls
    }
}

public enum FixtureError: Error, Equatable {
    case unknownFixture(String)
}
